### ISSUE TITLE
Async request caused an error: Invalid buffer id

### ISSUE THREAD

**Issue by zgpio** [numirias/semshi#44]
# Environment
* NVIM v0.4.0-1395-g3566267e7
* vim-fugitive: 645406f
* semshi: 527ebc5

# Reproduce
1. `nvim -u test_fugitive.vim`
2. `:UpdateRemotePlugins` and restart by `nvim -u test_fugitive.vim`
3. `:e ./semshi/setup.py`
4. `<Space>gi` and `<enter>`
5. You will see the error information
see [video](https://asciinema.org/a/C87Czt20K07Ws3CVcc6modvhu)

Sorry, I tried it, but I didn't find a way to directly reproduce the problem. I need to use `fugitive` to reproduce this problem, but I think this is related to `semshi`, so I report the problem here.

test_fugitive.vim
```vim
set runtimepath+=./vim-fugitive
set runtimepath+=./semshi

nnoremap <silent> <Space>gi :Git add -p %<CR>
```

**Comment by wookayin** [comment]
This bug is still present. @zgpio would you mind reopening this?

**Comment by wookayin** [comment]
This can actually happen due to many reasons --- the buffer might have been wiped out and the asynchronous call of updating buffer highlights gets executed after the buffer is gone. To avoid such race condition, we'll need to validate the existence of the buffer before making `call_atomic` (`nvim_buf_*`) calls.

I made [a patch that fixes this bug](https://github.com/wookayin/semshi/commit/678faa1) in my fork. Let me add a PR later (because the project is not maintained...)
