### ISSUE TITLE
How does it compare to vim-jedi

### ISSUE THREAD

**Issue by smartsammler** [numirias/semshi#7]
How does semshi compare to [vim-jedi](https://github.com/davidhalter/jedi-vim) beside that semshi is just for syntax highlighting whereas jedi does completion, showing docs and many more?

Of cause that are huge differences, but I'm curious if there might be more than that. Maybe a small comparison in the FAQ would be great.  

Thank you very much.

**Comment by numirias** [comment]
Thanks for checking out semshi.

> How does semshi compare to vim-jedi beside that semshi is just for syntax highlighting whereas jedi does completion, showing docs and many more?

Well, that's essentially it. Semshi does vastly improved code highlighting ("semantic highlighting") and while it has some refactoring capabilities, such as renaming nodes, that's not its main purpose. So it's perfectly reasonable to use semshi alongside vim-jedi and other completion/refactoring libs - it's in no way meant to replace them.

What it shares with those other tools is that they all do some form of static code analysis in the background. However, semshi has to be much faster in order to adjust highlights as you type.

Does that make sense to you? I'll see if I can put that in a FAQ section.

**Comment by smartsammler** [comment]
Thank you for your feedback.
Yes, it makes sense to me, and especially the point that it has to be fast and therefore is also meant to co-exist is a very valid point.
