### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by CrossR** [numirias/semshi#8]
Hi!

Wanted to give semshi a try out, but it looks like `nvim` has an issue with finding this plugin on Windows.

At a guess, I'd say its the symbolic link in the `rplugins/python3/` folder....but when I removed that and stuck the files directly in there I got a bunch of errors about `attempted relative import with no known parent package`.

I guess to tick off the other bits - 
* `:CheckHealth` reports no issues with python3.
* I've got some other plugins that require it too (ie `'mhartington/nvim-typescript'`). 
* My linux box with the same setup has no issues recognising Semshi. (Same Python ver + Nvim ver).
* Manually running `:UpdateRemotePlugins` doesn't find Semshi either, nor does having it run that command after installing with `plug-vim`.

Anything else I can help with let me know!

**Comment by numirias** [comment]
Thanks for your detailed report!

I'm not a regular Windows user, so it'll probably take me a bit to set up Neovim on Windows and check what's wrong here.

> but when I removed that and stuck the files directly in there I got a bunch of errors

The symlink being the problem seems like a good guess. Just to clarify, you got the error after copying all files from `semshi/` to `rplugins/python3/semshi` (including `__init__.py`)? If you find the time you may also want to try again *moving* the files, so that there is no more `semshi/` in the project.

I'll let you know when I got it sorted out.

**Comment by CrossR** [comment]
>Just to clarify, you got the error after copying all files from semshi/ to rplugins/python3/semshi (including \_\_init__.py)? 

Whoops, I'd copied it directly to `rplugins/python3/` rather than `rplugins/python3/semshi`, which would explain why the imports weren't happy.

Moving it to `rplugins/python3/semshi` fixed it for me in Nvim-QT on Windows. I get some issues still in Oni relating to:

```
        if not self._options.active: # pylint: disable=protected-access
AttributeError: 'NoneType' object has no attribute 'active'
```

But I can raise an issue for that over in the Oni repo and look into what may be causing it.

**Comment by numirias** [comment]
Thanks for checking! It seems Oni is raising events in a different order than Semshi expects. That's more or less Semshi's fault, but seems straightforward to fix.

**Comment by CrossR** [comment]
If it looks like Oni is doing anything odd, please shout up so me or one of the other devs can get it fixed! Would much rather have Oni behave like everything else, than have you need to rewrite something just for it.

**Comment by numirias** [comment]
@CrossR Semshi is doing some initialization on `BufEnter` which doesn't seem to get called when you open a file in Oni. Or it's called *after* other events such as `VimResized` or `TextChanged` where Semshi assumes that it has already been initialized.

I think I can do a better job ensuring initialization, but of course it would be awesome if Oni triggers events in the same order as Neovim since probably other plugins make similar assumptions.
