### ISSUE TITLE
Semshi's highlighting breaks when running any :syntax commands

### ISSUE THREAD

**Issue by drskoolie** [numirias/semshi#90]
Semshi's highlighting stops working when I run a command like `:syntax enable` and no matter what `:Semshi` commands I throw at it, it will not work again until I leave neovim and come back in. 

I have the above `:syntax enable` command in my `init.vim` and if I change anything in that file and source it, then highlighting stops working.

**Comment by DanielArndt** [comment]
Seems related to https://github.com/numirias/semshi/issues/70

I am also having this issue. It's annoying to have to quit vim to get it working again.

**Comment by blueyed** [comment]
Do you have a minimal reproducible example?
Just `:syntax enable` does not trigger it for me, but I sometimes see it going out of sync - not sure if that is what you're referring to as "stops working".

**Comment by blueyed** [comment]
FWIW, this could also be a bug/issue with Neovim, so posting version information in that regard is also useful.

**Comment by DanielArndt** [comment]
I sincerely apologize for wasting your time, my issue actually does not happen with `:syntax enable`. I erroneously reported that I have the same issue.

My issue is actually more closely related to #70 and I made a horrible assumption that `:syntax enable` fell in the same list of commands that trigger it. Specifically, my issue is that semshi's syntax highlighting disappears (it defaults to the vim built-in highlighting) when I use `set background=[light|dark]` or change the color scheme. The first being the most annoying of the two since I often switch when I travel indoors or go outside .

I won't distract from this issue with too many details since it appears unrelated, however I can provide more details in #70 if needed.

Sorry for the confusion.

**Comment by blueyed** [comment]
@DanielArndt 
Thanks for the clarification.
I've looked into this and #111 fixes it - likely also this issue / for @a-elhag (please test it).
